services:
  - type: web
    name: mypatterns-web
    env: docker
    dockerfilePath: ./Dockerfile
    branch: main
    autoDeploy: true
    plan: free

    envVars:
      - key: RAILS_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: mypatterns-db
          property: connectionString
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: RAILS_MASTER_KEY
        sync: false  
      - key: WEB_CONCURRENCY
        value: 1

databases:
  - name: mypatterns-db
    engine: postgresql
    plan: starter
    region: oregon
