
services:
  - type: web
    name: mypatterns-web
    env: docker
    dockerfilePath: ./Dockerfile
    branch: main
    autoDeploy: true
    plan: free
    envVars:
      - key: RAILS_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: mypatterns-db
          property: connectionString
      - key: SECRET_KEY_BASE
        fromSecret: rails-secret-key-base
      - key: DB_HOST
        value: <leave blank if using DATABASE_URL>
      - key: DB_USER
        value: <leave blank if using DATABASE_URL>
      - key: DB_PASSWORD
        value: <leave blank if using DATABASE_URL>

databases:
  - name: mypatterns-db
    engine: postgresql
    plan: starter
    region: oregon
