default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: mypatterns_development

test:
  <<: *default
  database: mypatterns_test

production:
  url: <%= ENV['DATABASE_URL'] %>

cache:
  url: <%= ENV['DATABASE_URL'] %>

queue:
  url: <%= ENV['DATABASE_URL'] %>

cable:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>

